export const GET_ALL_COUNTRY_CASES_LOADING = "GET_ALL_COUNTRY_CASES_LOADING";
export const GET_ALL_COUNTRY_CASES_SUCCESS = "GET_ALL_COUNTRY_CASES_SUCCESS";
export const GET_ALL_COUNTRY_CASES_ERROR = "GET_ALL_COUNTRY_CASES_ERROR";

export const GET_COUNTRY_CASES_LOADING = "GET_COUNTRY_CASES_LOADING";
export const GET_COUNTRY_CASES_SUCCESS = "GET_COUNTRY_CASES_SUCCESS";
export const GET_COUNTRY_CASES_ERROR = "GET_COUNTRY_CASES_ERROR";

export const GET_COUNTRY_CODES_LOADING = "GET_COUNTRY_CODES_LOADING";
export const GET_COUNTRY_CODES_SUCCESS = "GET_COUNTRY_CODES_SUCCESS";
export const GET_COUNTRY_CODES_ERROR = "GET_COUNTRY_CODES_ERROR";
